problem: 1050
# path
schema_path: "/home/ruidong/SQL_Optimization_Calcite/benchmarks/calcite_schemas/calcite_sales.json"
constraint_path: "constraints"
sizes: [100, 100, 100, 100] # size of each table in testing database
trials: 50          # maximum number of trials that the tester can try if use random 
ordered: False           # if the order of rows in the output matter

tester:
  log_seed: True
  psql:
    dbname: tester
    username: vldb
    password: VLDB2022
    host: localhost
